### PR TITLE
Cleanup Textures tutorial

### PR DESCRIPTION
**Pull request by kanerogers**
I have broadly made three sets of changes:

1. General prose cleanup (eg. correcting minor syntax errors, rewriting some sentences to make them more clear)
2. Code consistency (eg. not making use of the `texture` wrapper until it is defined at the end of the page, not redefining the `size` variable, not declaring unused fields on `State`).
3. Adding necessary dependencies to `Cargo.toml`.

Please feel free to reject/challenge any of these changes as you see fit! I have tried to keep your (@sotrh) voice as consistent as possible, but if that's not the case, please just let me know.

### CODE REVIEW

**Review by sotrh — CHANGES_REQUESTED** [review]
I'm not comfortable with removing the `texture`, `sampler`, and `texture_view` as they are used in the depth buffer tutorial. Beyond that all other tutorials beyond this one would need to be changed as they include a `texture::Texture` field.

Also if the user needs to rebind the texture at any point (say they want to use a different sampler/texture view) they need access to at least the original `wgpu::Texture`. AFAIK there is no way to retrieve the texture, sampler, and texture view from the existing bind group.

While I do feel that how I'm handling textures throughout the tutorials needs to be rethought, I feel that should be it's own issue. I mostly wanted to clean up the typos and code inconsistencies in this pass.

**Comment by kanerogers** [comment]
No stress, that’s totally your call. :)

FWIW I haven’t completed the tutorial yet and so I wasn’t aware they’re
used later. Maybe a note to indicate they will be used later might help?

I’ll make those changes tomorrow.

Thanks,
Kane

**Comment by kanerogers** [comment]
@sotrh Done! I omitted `sampler` and `texture_view` as these are actually included in `texture::Texture` already. 

I thought it easier to just add it at the end of the tutorial, rather than add extra cognitive load by adding the field and then removing it later on. If this isn't what you're after, I'd be happy to change it back. 😄

**Review by sotrh — APPROVED** [review]

**Comment by kanerogers** [comment]
Awesome. Thank you!

**Pull request merged**
