### PR TITLE
Except cfg_if crate dependencies

### PR DESCRIPTION
**Pull request by 8picoz**
#339 
Replaced code using `cfg_if`

### CODE REVIEW

**Comment by sotrh** [comment]
What's the motivation for this?

**Comment by 8picoz** [comment]
@sotrh 
At first I just created [docs ](https://github.com/sotrh/learn-wgpu/pull/339) that would add `cfg_if` to Cargo.toml.
But I thought I could run it on without depending on A.
Less other crate dependence is better.

**Comment by sotrh** [comment]
I chose to use `cfg-if` as it simplifies including/excluding code at compile time in a more readable manner. I like the if-else style more than the `#[cfg(not(...))]` boiler plate that you would have to do with just `cfg`.

**Comment by 8picoz** [comment]
Ok, I got it.
Thank you.

**Pull request closed without merging**
